export const categories = [
  'Technology',
  'Design',
  'Business',
  'Arts',
  'Science',
  'Sports',
  'Education',
  'Social Impact',
  'Other',
] as const

export type Category = typeof categories[number]

export const subcategories: Record<Category, string[]> = {
  Technology: [
    'Web Development',
    'Mobile Development',
    'AI & Machine Learning',
    'Data Science',
    'Cybersecurity',
    'Blockchain & Crypto',
    'Cloud Computing',
    'DevOps',
    'Game Development',
    'IoT & Hardware',
    'Software Engineering',
    'Open Source',
  ],
  Design: [
    'UI/UX Design',
    'Graphic Design',
    'Product Design',
    'Fashion Design',
    'Interior Design',
    'Industrial Design',
    'Architecture',
    'Animation',
    'Motion Graphics',
    'Branding & Identity',
    'Web Design',
    'Illustration',
  ],
  Business: [
    'Startup Pitch',
    'Business Plan',
    'Marketing Strategy',
    'E-commerce',
    'Finance & Accounting',
    'Entrepreneurship',
    'Innovation',
    'Social Enterprise',
    'Consulting',
    'Real Estate',
    'Supply Chain',
    'Operations',
  ],
  Arts: [
    'Visual Arts',
    'Performing Arts',
    'Music',
    'Film & Video',
    'Photography',
    'Writing & Literature',
    'Poetry',
    'Theater',
    'Dance',
    'Sculpture',
    'Digital Art',
    'Mixed Media',
  ],
  Science: [
    'Biology',
    'Chemistry',
    'Physics',
    'Mathematics',
    'Environmental Science',
    'Medical Research',
    'Astronomy',
    'Engineering',
    'Materials Science',
    'Psychology',
    'Neuroscience',
    'Biotechnology',
  ],
  Sports: [
    'Team Sports',
    'Individual Sports',
    'E-sports',
    'Fitness & Wellness',
    'Adventure Sports',
    'Water Sports',
    'Winter Sports',
    'Combat Sports',
    'Racing',
    'Extreme Sports',
    'Traditional Sports',
    'Recreational Sports',
  ],
  Education: [
    'Online Learning',
    'Educational Technology',
    'Curriculum Development',
    'Language Learning',
    'STEM Education',
    'Early Childhood',
    'Higher Education',
    'Vocational Training',
    'Special Education',
    'Teacher Training',
    'Educational Research',
    'Student Projects',
  ],
  'Social Impact': [
    'Community Development',
    'Environmental Conservation',
    'Healthcare Access',
    'Education Equity',
    'Poverty Alleviation',
    'Gender Equality',
    'Mental Health',
    'Disaster Relief',
    'Human Rights',
    'Sustainable Development',
    'Youth Empowerment',
    'Elderly Care',
  ],
  Other: [
    'General',
    'Miscellaneous',
    'Cross-Disciplinary',
    'Experimental',
    'Research',
    'Innovation Challenge',
  ],
}

export function getSubcategories(category: Category | string): string[] {
  if (!category || !categories.includes(category as Category)) {
    return []
  }
  return subcategories[category as Category] || []
}


