name: Simple SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to EC2
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no root@147.182.206.208 << 'EOF'
            cd ~/taakra/http &&

            git pull origin main &&

            pnpm install &&

            pm2 delete taakra || true &&

            pm2 start "pnpm dev" --name taakra &&

            pm2 save &&

            echo "Dev deployed successfully!!!!!"
          EOF
